
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb

  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - "8000:80"
      - '443:443'
    volumes:
      - wordpress_data:/bitnami/wordpress
      - apache_data:/bitnami/apache
      - php_data:/bitnami/php
    environment:
      PLUGINS: >-
        advanced-custom-fields

  frontend:
    build: ./frontend
    command: node_modules/.bin/nodemon index.js
    environment:
      NODE_ENV: development
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/usr/src/app:ro

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local